"""Night Recap — Sonnet-written morning-after summary of the prior day's picks.

Generated by the grader once a date's picks finish grading. Stored in
data/night_recaps.json keyed by date. The site renders the most recent
recap prominently when today_picks is empty (i.e. between 11:30 PM grading
and 11 AM next-day lock).
"""
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Optional

import anthropic

from engine.utils import (
    get_logger, nyc_now, read_json, write_json,
    estimate_cost, record_api_cost, DATA_DIR, PROJECT_ROOT
)

logger = get_logger("night-recap")

RECAPS_PATH = DATA_DIR / "night_recaps.json"
PROMPT_PATH = PROJECT_ROOT / "prompts" / "night-recap-system.md"
MODEL = "claude-sonnet-4-6"


def _load_recaps() -> dict:
    return read_json(RECAPS_PATH, {})


def _save_recaps(recaps: dict) -> None:
    write_json(RECAPS_PATH, recaps)


def generate_recap(date_str: str, picks: list[dict],
                   ladder_state: Optional[dict] = None) -> Optional[dict]:
    """Generate the night-summary for a given date's graded picks.

    Skips bonus picks (they aren't part of the official record).
    Returns the recap dict on success, None on failure / nothing to recap.
    """
    main_picks = [p for p in picks
                  if p.get("date") == date_str
                  and not p.get("bonus_pick")
                  and p.get("status") in ("WIN", "LOSS", "PUSH")]
    if not main_picks:
        logger.info(f"No graded main picks for {date_str} — no recap")
        return None

    api_key = os.getenv("ANTHROPIC_API_KEY", "")
    if not api_key:
        logger.warning("No ANTHROPIC_API_KEY — skipping recap")
        return None

    if not PROMPT_PATH.exists():
        logger.error(f"Recap prompt missing: {PROMPT_PATH}")
        return None
    system_prompt = PROMPT_PATH.read_text()

    # Compact picks summary for the model
    summary = []
    for p in main_picks:
        summary.append({
            "pick": p.get("pick"),
            "game": p.get("game"),
            "odds": p.get("best_odds"),
            "units": p.get("units"),
            "status": p.get("status"),
            "result_score": p.get("result_score"),
            "units_result": p.get("units_result"),
            "ladder": bool(p.get("ladder_designation")),
            "autopsy": p.get("autopsy"),
        })

    user_msg = (
        f"Night recap for {date_str}. Use web_search if you need to verify "
        f"a key moment that decided a pick. Return strict JSON.\n\n"
        f"{json.dumps({'date': date_str, 'picks': summary, 'ladder': ladder_state or {}}, indent=2, default=str)}"
    )

    try:
        client = anthropic.Anthropic(api_key=api_key)
        messages = [{"role": "user", "content": user_msg}]
        final_text = ""
        for _ in range(8):
            msg = client.messages.create(
                model=MODEL,
                max_tokens=1200,
                temperature=0.3,
                system=system_prompt,
                tools=[{"type": "web_search_20250305", "name": "web_search", "max_uses": 3}],
                messages=messages,
            )
            if msg.usage:
                cost = estimate_cost(MODEL, msg.usage.input_tokens, msg.usage.output_tokens)
                record_api_cost(cost)
            if msg.stop_reason != "tool_use":
                for block in (msg.content or []):
                    if getattr(block, "type", "") == "text":
                        final_text += getattr(block, "text", "")
                break
            messages.append({"role": "assistant", "content": msg.content})
        from engine.handicapper import _extract_json, _robust_json_loads
        js = _extract_json(final_text)
        if not js:
            logger.error(f"No JSON in recap response: {final_text[:200]}")
            return None
        recap = _robust_json_loads(js, final_text)
    except Exception as e:
        logger.error(f"Night recap API call failed: {e}")
        return None

    record = {
        "date": date_str,
        "record": recap.get("record", ""),
        "units_pl": recap.get("units_pl", 0),
        "night_summary": recap.get("night_summary", ""),
        "generated_at": nyc_now().isoformat(),
    }
    recaps = _load_recaps()
    recaps[date_str] = record
    _save_recaps(recaps)
    logger.info(f"Night recap written for {date_str} ({record['record']}, {record['units_pl']:+.2f}u)")
    return record


def latest_recap() -> Optional[dict]:
    """Return the most recent recap dict, or None."""
    recaps = _load_recaps()
    if not recaps:
        return None
    latest_date = max(recaps.keys())
    return recaps[latest_date]
